apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ocp4x-ptp
spec:
  selector:
      matchLabels:
        name: ocp4x-ptp 
  template:
    metadata:
      labels:
        name: ocp4x-ptp 
    spec:
      nodeSelector: 
        type: worker
      containers:
      - image: ocp4x-telco/ptp
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: 200Mi
        #   requests:
        #     cpu: 100m
        #     memory: 200Mi
        name: linuxptp
        resources: {}
        terminationMessagePath: /dev/termination-log
      serviceAccount: ocp4x-ptp-sa
      terminationGracePeriodSeconds: 10